/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * NXP Wireless LAN device driver: VENDOR
 *
 * Copyright 2011-2024 NXP
 */

#ifndef __NXPWIFI_VENDOR_H__
#define __NXPWIFI_VENDOR_H__

#define NXP_OUI	0x006037

enum nxpwifi_vendor_commands {
	NXPWIFI_VENDOR_CMD_HSCFG,
	NXPWIFI_VENDOR_CMD_SLEEPPD,
	NXPWIFI_VENDOR_CMD_CLOCKSYNC,
	NXPWIFI_VENDOR_CMD_HSOFFLD,
	NXPWIFI_VENDOR_CMD_INDRST,
	NXPWIFI_VENDOR_CMD_SETCSI,
	NXPWIFI_VENDOR_CMD_CHSWITCH,
	NXPWIFI_VENDOR_CMD_ANTCFG,
	NXPWIFI_VENDOR_CMD_EDMAC_CFG,
	NXPWIFI_VENDOR_CMD_VHT_CFG,
	NXPWIFI_VENDOR_CMD_TXPOWER_LIMIT
};

enum nxpwifi_rawdata_attrs {
	NXPWIFI_HSCFG = 1,
	NXPWIFI_SLEEPPD,
	NXPWIFI_TSF_REPORT,
	NXPWIFI_HS_OFFLOAD,
	NXPWIFI_INDRST_CFG,
	NXPWIFI_ATTR_CSI_CONFIG,
	NXPWIFI_ATTR_MAC_ADDR,
	NXPWIFI_ATTR_CHSWITCH,
	NXPWIFI_ATTR_ANTENNA_MODE,
	NXPWIFI_ATTR_SAD_EVAL_TIME,
	NXPWIFI_ATTR_TXPWR_LIMIT,
	NXPWIFI_ATTR_CSI_MAX
};

enum nxpwifi_edmac_attrs {
	NXPWIFI_EDMAC_CTRL_2G = 1,
	NXPWIFI_EDMAC_OFFSET_2G,
	NXPWIFI_EDMAC_CTRL_5G,
	NXPWIFI_EDMAC_OFFSET_5G,
	NXPWIFI_EDMAC_TXQ_LOCK,
	NXPWIFI_EDMAC_MAX
};

enum nxpwifi_vht_attrs {
	NXPWIFI_VHT_BAND = 1,
	NXPWIFI_VHT_TXRX,
	NXPWIFI_VHT_BW,
	NXPWIFI_VHT_CAP,
	NXPWIFI_VHT_TXMCS,
	NXPWIFI_VHT_RXMCS,
	NXPWIFI_VHT_MAX
};

#define HS_OFFLOAD_ARP 0x1
#define HS_OFFLOAD_PING 0x2
#define HS_WAKEON_MDNS 0x4

void nxpwifi_set_vendor_commands(struct wiphy *wiphy);
#endif /* __NXPWIFI_VENDOR_H__ */
